name: test-coverage
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup yarn package manager
        uses: c-hive/gha-yarn-cache@v2
      - name: Install JS dependencies
        run: yarn install
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
