name: test-coverage
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: acti  ons/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
